### ISSUE TITLE
vue compiler removed duplicate style name

### ISSUE THREAD

**Issue by voorjaar** [windicss/vue-windicss-preprocess#1]
vue compiler will delete duplicate style names, which will cause cross-browser support failed.

```css
/* example */
.flex {
  display: -webkit-box;
  display: -ms-flexbox;
  display: -webkit-flex;
  display: flex;
}

/* vue compiled */
.flex {
  display: flex;
}
```
