### ISSUE TITLE
Duplicate global/preflight injections

### ISSUE THREAD

**Issue by danielroe** [windicss/vue-windicss-preprocess#10]
Using Nuxt, in my final CSS I have an additional copy of all global styles for every component added to the `<head>`. For example, the following CSS could easily be repeated 10-20x:
```css
body {
    margin: 0;
    font-family: inherit;
    line-height: inherit;
}
* {
    --tw-ring-inset: var(--tw-empty, );
    --tw-ring-offset-width: 0px;
    --tw-ring-offset-color: #fff;
    --tw-ring-color: rgba(59,130,246,0.5);
    --tw-ring-offset-shadow: 0 0 transparent;
    --tw-ring-shadow: 0 0 transparent;
    --tw-shadow: 0 0 transparent;
}
// etc.
```
